Repository Conexao-Saudavel/app-conexao-saudavel, pull requests merged in 2025-05, with the labels that each got.

#49 Remoção de bloqueador de apps para o usuário
  mobile/src/navigation/MainNavigator.tsx
  mobile/src/screens/dashboard/BlockAppsScreen.tsx
  mobile/src/screens/dashboard/DashboardScreen.tsx
Labels: documentation

#50 Remove o círculo do avatar na DashboardScreen
  mobile/src/screens/dashboard/DashboardScreen.tsx
Labels: enhancement

#51 Criação da página de esquecer senha
  mobile/src/components/auth/ForgotPasswordForm.tsx
  mobile/src/navigation/AuthNavigator.tsx
  mobile/src/navigation/MainNavigator.tsx
  mobile/src/screens/auth/ForgotPasswordScreen.tsx
  mobile/src/screens/auth/LoginScreen.tsx
  mobile/src/screens/dashboard/DashboardScreen.tsx
  mobile/src/screens/dashboard/ReflectiveDiaryScreen.tsx
Labels: enhancement

#53 Atualização da Paleta de Cores do Layout e Documentação de Design
  mobile/src/screens/dashboard/DashboardScreen.tsx
  mobile/src/screens/dashboard/UsageChartsScreen.tsx
  mobile/src/theme/colors.ts
Labels: documentation, duplicate

#55 Adição de Menu Hambúrguer e Atualização da Tela de Registro
  assets/logo-com-fundo.png
  package-lock.json
  package.json
  src/components/auth/RegistrationForm.tsx
  src/components/layout/DrawerMenu.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/dashboard/DashboardScreen.tsx
  src/types/auth.ts
Labels: enhancement
